#!/usr/bin/expect -f
# Copyright (C) 2017  Gradiant <https://www.gradiant.org/>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

# set variables
set idm_password $$IDM_PASS
spawn sudo tools/with_venv.sh bin/keystone-manage db_sync --populate

# Look for prompt
expect "Set a password for the idm user. (If you forget it, the password can be changed later using the admin token): "

# Send password aka $idm_password
send -- "$idm_password\r"

expect eof
